### ISSUE TITLE
Camera System Hardware Selection

### ISSUE THREAD

**Issue by co-li** [WisconsinRobotics/WRover_Software#70]
# Rationale

The Raspberry Pi might not be powerful enough for streaming camera feeds.
Electrical has proposed using a co-processor to handle video streaming.

# Required Actions

- [ ] Discuss potential co-processors with Electrical
- [ ] Document options and decisions made in this issue

**Comment by Tzanccc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Camera System Hardware Selection](https://trello.com/c/IboNXkbN/115-camera-system-hardware-selection)
