### ISSUE TITLE
Implement search pattern for shortrange AI

### ISSUE THREAD

**Issue by co-li** [WisconsinRobotics/WRover_Software#73]
# Rationale

The rover may need to move in a search pattern to find the vision targets during autonomous navigation.

# Required Actions

- [ ] Potential blocker: shortrange AI code may need to be refactored and/or documented
- [ ] Discuss possible search patterns
- [ ] Implement a search pattern
- [x] #82

**Comment by Tzanccc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Search Pattern for Shortrange AI](https://trello.com/c/rz6UyAcz/112-implement-search-pattern-for-shortrange-ai)

**Comment by rusmilov** [comment]
- [ ] Finalize search pattern
- [ ] Read the documentation for wr_ai_logic
- [ ] Start implementing
