### ISSUE TITLE
ROS 2 Migration Plan

### ISSUE THREAD

**Issue by co-li** [WisconsinRobotics/WRover_Software#74]
# Rationale

The rover software should eventually be migrated to ROS 2 to take advantage of new feature and use actively developed libraries.

# Required Actions

- [ ] Research ROS 2 and how it differs from ROS 1
- [ ] Read the documentation for [Migrating from ROS 1 to ROS 2](https://docs.ros.org/en/iron/How-To-Guides/Migrating-from-ROS1.html)
- [ ] Develop a migration plan for switching rover software to ROS 2

**Comment by co-li** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Look into upgrading to ROS Noetic](https://trello.com/c/iPnJaryb/63-look-into-upgrading-to-ros-noetic)

**Comment by Tzanccc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ROS 2 Migration Plan](https://trello.com/c/LCWERgWe/119-ros-2-migration-plan)
