### ISSUE TITLE
Document wr_logic_ai

### ISSUE THREAD

**Issue by co-li** [WisconsinRobotics/WRover_Software#77]
# Rationale
Sustain the maintainability of the design for Wisconsin Robotics Software.

# Required Actions

- [ ] Refactor shortrange AI to remove gate code
- [ ] Update documentation for wr_logic_ai package

**Comment by Tzanccc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documenting wr_logic_ai package](https://trello.com/c/pnbeBabD/124-documenting-wrlogicai-package)
