### ISSUE TITLE
Research DGNSS's benefits and possible issues

### ISSUE THREAD

**Issue by LetianLi** [WisconsinRobotics/WRover_Software#84]
# Rationale

Before directly implementing DGNSS in #80, look into what will be needed, how to actually do this calculation, and more.

# Required Actions

- [x] Research accuracy improvement
- [x] Research possible issues
- [x] Research required hardware
- [x] Communicate any requirements to Hardware and Electrical
- [x] Figure out equation and how to supply equation variables.

**Comment by LetianLi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Differential GNSS System](https://trello.com/c/G413YKPF/125-implement-differential-gnss-system)

**Comment by LetianLi** [comment]
https://novatel.com/an-introduction-to-gnss

**Comment by LetianLi** [comment]
We'll need to wait for Electrical to come up with a plan on exactly how they want to set up the system.

I see a few options for this.
- Communicate directly between base and RTK board with radio and directly publish correction data.
- Embed gps base data directly into ros and publish to rover and pull into RTK board (more complex and harder?)

**Comment by LetianLi** [comment]
With the ArduSimple [board](https://www.ardusimple.com/product/simplertk2b/), we can either get 2 for both the rover and base, or we use some other gps receiver at the base to save on costs. That's another complexity but it's for Electrical to handle for now.

**Comment by ksha23** [comment]
I was under the impression, from reading docs that if we buy the simple starter kit, it would broadcast correction data to the rover by itself (implemented by the manufacturer) already. We would just need to pull in data from the receiver on the rover?

**Comment by ksha23** [comment]
I think we're trying to find where in the code the lat/long and other GPS data is used

**Comment by LetianLi** [comment]
The kit handles radio communications for us, but personally, I'm against adding even more antennas for communication when we already have radio antennas set up and also since it would be more expensive.

I think we should try to figure out how to
1. get correction gps data out of the board
2. send it to the rover (broadcast topic)
3. send it into the rover board there (not sure how)
4. get corrected position out of the board
